THIRD_PARTY_INCLUDES_START
#pragma warning (disable : 4005)
#pragma warning (disable : 4125)
// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: unaryDemo.proto
#ifndef GRPC_unaryDemo_2eproto__INCLUDED
#define GRPC_unaryDemo_2eproto__INCLUDED

#include "unaryDemo.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class UnaryDemoService final {
 public:
  static constexpr char const* service_full_name() {
    return "UnaryDemoService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Request(::grpc::ClientContext* context, const ::UnaryDemoRequest& request, ::UnaryDemoResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UnaryDemoResponse>> AsyncRequest(::grpc::ClientContext* context, const ::UnaryDemoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UnaryDemoResponse>>(AsyncRequestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UnaryDemoResponse>> PrepareAsyncRequest(::grpc::ClientContext* context, const ::UnaryDemoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UnaryDemoResponse>>(PrepareAsyncRequestRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Request(::grpc::ClientContext* context, const ::UnaryDemoRequest* request, ::UnaryDemoResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Request(::grpc::ClientContext* context, const ::UnaryDemoRequest* request, ::UnaryDemoResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::UnaryDemoResponse>* AsyncRequestRaw(::grpc::ClientContext* context, const ::UnaryDemoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::UnaryDemoResponse>* PrepareAsyncRequestRaw(::grpc::ClientContext* context, const ::UnaryDemoRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Request(::grpc::ClientContext* context, const ::UnaryDemoRequest& request, ::UnaryDemoResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UnaryDemoResponse>> AsyncRequest(::grpc::ClientContext* context, const ::UnaryDemoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UnaryDemoResponse>>(AsyncRequestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UnaryDemoResponse>> PrepareAsyncRequest(::grpc::ClientContext* context, const ::UnaryDemoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UnaryDemoResponse>>(PrepareAsyncRequestRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Request(::grpc::ClientContext* context, const ::UnaryDemoRequest* request, ::UnaryDemoResponse* response, std::function<void(::grpc::Status)>) override;
      void Request(::grpc::ClientContext* context, const ::UnaryDemoRequest* request, ::UnaryDemoResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::UnaryDemoResponse>* AsyncRequestRaw(::grpc::ClientContext* context, const ::UnaryDemoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::UnaryDemoResponse>* PrepareAsyncRequestRaw(::grpc::ClientContext* context, const ::UnaryDemoRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Request_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Request(::grpc::ServerContext* context, const ::UnaryDemoRequest* request, ::UnaryDemoResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Request() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Request(::grpc::ServerContext* /*context*/, const ::UnaryDemoRequest* /*request*/, ::UnaryDemoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequest(::grpc::ServerContext* context, ::UnaryDemoRequest* request, ::grpc::ServerAsyncResponseWriter< ::UnaryDemoResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Request<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Request() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::UnaryDemoRequest, ::UnaryDemoResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::UnaryDemoRequest* request, ::UnaryDemoResponse* response) { return this->Request(context, request, response); }));}
    void SetMessageAllocatorFor_Request(
        ::grpc::MessageAllocator< ::UnaryDemoRequest, ::UnaryDemoResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::UnaryDemoRequest, ::UnaryDemoResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Request(::grpc::ServerContext* /*context*/, const ::UnaryDemoRequest* /*request*/, ::UnaryDemoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Request(
      ::grpc::CallbackServerContext* /*context*/, const ::UnaryDemoRequest* /*request*/, ::UnaryDemoResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Request<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Request() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Request(::grpc::ServerContext* /*context*/, const ::UnaryDemoRequest* /*request*/, ::UnaryDemoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Request() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Request(::grpc::ServerContext* /*context*/, const ::UnaryDemoRequest* /*request*/, ::UnaryDemoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequest(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Request() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Request(context, request, response); }));
    }
    ~WithRawCallbackMethod_Request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Request(::grpc::ServerContext* /*context*/, const ::UnaryDemoRequest* /*request*/, ::UnaryDemoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Request(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Request : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Request() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::UnaryDemoRequest, ::UnaryDemoResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::UnaryDemoRequest, ::UnaryDemoResponse>* streamer) {
                       return this->StreamedRequest(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Request() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Request(::grpc::ServerContext* /*context*/, const ::UnaryDemoRequest* /*request*/, ::UnaryDemoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRequest(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::UnaryDemoRequest,::UnaryDemoResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Request<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Request<Service > StreamedService;
};


#endif  // GRPC_unaryDemo_2eproto__INCLUDED
THIRD_PARTY_INCLUDES_END
