version: "3.9"
services:
  server:
    build: .
    volumes:
      - .:/usr/demoServer
    working_dir: /usr/demoServer
    environment:
      - SERVER_PORT=8000
    ports:
      - 8000:8000
    entrypoint: "make buildAndRun"
