THIRD_PARTY_INCLUDES_START
#pragma warning (disable : 4005)
#pragma warning (disable : 4125)
// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: clientStreamingDemo.proto
#ifndef GRPC_clientStreamingDemo_2eproto__INCLUDED
#define GRPC_clientStreamingDemo_2eproto__INCLUDED

#include "clientStreamingDemo.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpcDemo {

class ClinentStreamingDemoService final {
 public:
  static constexpr char const* service_full_name() {
    return "grpcDemo.ClinentStreamingDemoService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientWriterInterface< ::grpcDemo::UploadClientTextureRequest>> UploadTexture(::grpc::ClientContext* context, ::grpcDemo::UploadClientTextureResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::grpcDemo::UploadClientTextureRequest>>(UploadTextureRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::grpcDemo::UploadClientTextureRequest>> AsyncUploadTexture(::grpc::ClientContext* context, ::grpcDemo::UploadClientTextureResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::grpcDemo::UploadClientTextureRequest>>(AsyncUploadTextureRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::grpcDemo::UploadClientTextureRequest>> PrepareAsyncUploadTexture(::grpc::ClientContext* context, ::grpcDemo::UploadClientTextureResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::grpcDemo::UploadClientTextureRequest>>(PrepareAsyncUploadTextureRaw(context, response, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void UploadTexture(::grpc::ClientContext* context, ::grpcDemo::UploadClientTextureResponse* response, ::grpc::ClientWriteReactor< ::grpcDemo::UploadClientTextureRequest>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientWriterInterface< ::grpcDemo::UploadClientTextureRequest>* UploadTextureRaw(::grpc::ClientContext* context, ::grpcDemo::UploadClientTextureResponse* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::grpcDemo::UploadClientTextureRequest>* AsyncUploadTextureRaw(::grpc::ClientContext* context, ::grpcDemo::UploadClientTextureResponse* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::grpcDemo::UploadClientTextureRequest>* PrepareAsyncUploadTextureRaw(::grpc::ClientContext* context, ::grpcDemo::UploadClientTextureResponse* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientWriter< ::grpcDemo::UploadClientTextureRequest>> UploadTexture(::grpc::ClientContext* context, ::grpcDemo::UploadClientTextureResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::grpcDemo::UploadClientTextureRequest>>(UploadTextureRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::grpcDemo::UploadClientTextureRequest>> AsyncUploadTexture(::grpc::ClientContext* context, ::grpcDemo::UploadClientTextureResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::grpcDemo::UploadClientTextureRequest>>(AsyncUploadTextureRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::grpcDemo::UploadClientTextureRequest>> PrepareAsyncUploadTexture(::grpc::ClientContext* context, ::grpcDemo::UploadClientTextureResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::grpcDemo::UploadClientTextureRequest>>(PrepareAsyncUploadTextureRaw(context, response, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void UploadTexture(::grpc::ClientContext* context, ::grpcDemo::UploadClientTextureResponse* response, ::grpc::ClientWriteReactor< ::grpcDemo::UploadClientTextureRequest>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientWriter< ::grpcDemo::UploadClientTextureRequest>* UploadTextureRaw(::grpc::ClientContext* context, ::grpcDemo::UploadClientTextureResponse* response) override;
    ::grpc::ClientAsyncWriter< ::grpcDemo::UploadClientTextureRequest>* AsyncUploadTextureRaw(::grpc::ClientContext* context, ::grpcDemo::UploadClientTextureResponse* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::grpcDemo::UploadClientTextureRequest>* PrepareAsyncUploadTextureRaw(::grpc::ClientContext* context, ::grpcDemo::UploadClientTextureResponse* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_UploadTexture_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status UploadTexture(::grpc::ServerContext* context, ::grpc::ServerReader< ::grpcDemo::UploadClientTextureRequest>* reader, ::grpcDemo::UploadClientTextureResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_UploadTexture : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UploadTexture() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_UploadTexture() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadTexture(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::grpcDemo::UploadClientTextureRequest>* /*reader*/, ::grpcDemo::UploadClientTextureResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUploadTexture(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpcDemo::UploadClientTextureResponse, ::grpcDemo::UploadClientTextureRequest>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_UploadTexture<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_UploadTexture : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UploadTexture() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpcDemo::UploadClientTextureRequest, ::grpcDemo::UploadClientTextureResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpcDemo::UploadClientTextureResponse* response) { return this->UploadTexture(context, response); }));
    }
    ~WithCallbackMethod_UploadTexture() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadTexture(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::grpcDemo::UploadClientTextureRequest>* /*reader*/, ::grpcDemo::UploadClientTextureResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpcDemo::UploadClientTextureRequest>* UploadTexture(
      ::grpc::CallbackServerContext* /*context*/, ::grpcDemo::UploadClientTextureResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_UploadTexture<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_UploadTexture : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UploadTexture() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_UploadTexture() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadTexture(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::grpcDemo::UploadClientTextureRequest>* /*reader*/, ::grpcDemo::UploadClientTextureResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_UploadTexture : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UploadTexture() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_UploadTexture() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadTexture(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::grpcDemo::UploadClientTextureRequest>* /*reader*/, ::grpcDemo::UploadClientTextureResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUploadTexture(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UploadTexture : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UploadTexture() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->UploadTexture(context, response); }));
    }
    ~WithRawCallbackMethod_UploadTexture() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadTexture(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::grpcDemo::UploadClientTextureRequest>* /*reader*/, ::grpcDemo::UploadClientTextureResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* UploadTexture(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace grpcDemo


#endif  // GRPC_clientStreamingDemo_2eproto__INCLUDED
THIRD_PARTY_INCLUDES_END
