version: "3.9"
services:
  generate:
    build: .
    volumes:
      - .:/usr/build/proto
      - ../server/proto:/usr/build/server/proto
      - ../gRPCDemoProject/Plugins/gRPCClient/source/gRPCClient/Private/proto:/usr/build/gRPCDemoProject/Plugins/gRPCClient/source/gRPCClient/Private/proto
    working_dir: /usr/build/proto
    entrypoint: "make generate"
