// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: serverStreamingDemo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetServerStreamingTextureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageName string `protobuf:"bytes,1,opt,name=imageName,proto3" json:"imageName,omitempty"`
}

func (x *GetServerStreamingTextureRequest) Reset() {
	*x = GetServerStreamingTextureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverStreamingDemo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerStreamingTextureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStreamingTextureRequest) ProtoMessage() {}

func (x *GetServerStreamingTextureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serverStreamingDemo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStreamingTextureRequest.ProtoReflect.Descriptor instead.
func (*GetServerStreamingTextureRequest) Descriptor() ([]byte, []int) {
	return file_serverStreamingDemo_proto_rawDescGZIP(), []int{0}
}

func (x *GetServerStreamingTextureRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

type GetServerStreamingTextureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *GetServerStreamingTextureResponse) Reset() {
	*x = GetServerStreamingTextureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverStreamingDemo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerStreamingTextureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStreamingTextureResponse) ProtoMessage() {}

func (x *GetServerStreamingTextureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_serverStreamingDemo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStreamingTextureResponse.ProtoReflect.Descriptor instead.
func (*GetServerStreamingTextureResponse) Descriptor() ([]byte, []int) {
	return file_serverStreamingDemo_proto_rawDescGZIP(), []int{1}
}

func (x *GetServerStreamingTextureResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type GetServerStreamingMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetServerStreamingMessageRequest) Reset() {
	*x = GetServerStreamingMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverStreamingDemo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerStreamingMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStreamingMessageRequest) ProtoMessage() {}

func (x *GetServerStreamingMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serverStreamingDemo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStreamingMessageRequest.ProtoReflect.Descriptor instead.
func (*GetServerStreamingMessageRequest) Descriptor() ([]byte, []int) {
	return file_serverStreamingDemo_proto_rawDescGZIP(), []int{2}
}

func (x *GetServerStreamingMessageRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetServerStreamingMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetServerStreamingMessageResponse) Reset() {
	*x = GetServerStreamingMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serverStreamingDemo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerStreamingMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStreamingMessageResponse) ProtoMessage() {}

func (x *GetServerStreamingMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_serverStreamingDemo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStreamingMessageResponse.ProtoReflect.Descriptor instead.
func (*GetServerStreamingMessageResponse) Descriptor() ([]byte, []int) {
	return file_serverStreamingDemo_proto_rawDescGZIP(), []int{3}
}

func (x *GetServerStreamingMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_serverStreamingDemo_proto protoreflect.FileDescriptor

var file_serverStreamingDemo_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e,
	0x67, 0x44, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x72, 0x70,
	0x63, 0x44, 0x65, 0x6d, 0x6f, 0x22, 0x40, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x54, 0x65, 0x78, 0x74, 0x75,
	0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x39, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x54, 0x65, 0x78,
	0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x22, 0x38, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3d, 0x0a, 0x21,
	0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69,
	0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xf8, 0x01, 0x0a, 0x1a,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x44,
	0x65, 0x6d, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x69, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x54, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x12, 0x2a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x44,
	0x65, 0x6d, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x54, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x44, 0x65, 0x6d, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69,
	0x6e, 0x67, 0x54, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x6f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6d, 0x70,
	0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x44, 0x65, 0x6d, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x44, 0x65, 0x6d, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x2d, 0x61, 0x6b, 0x61, 0x68, 0x6f, 0x72, 0x69, 0x2d, 0x72,
	0x61, 0x6d, 0x65, 0x6e, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x55, 0x45, 0x34, 0x44, 0x65, 0x6d, 0x6f,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_serverStreamingDemo_proto_rawDescOnce sync.Once
	file_serverStreamingDemo_proto_rawDescData = file_serverStreamingDemo_proto_rawDesc
)

func file_serverStreamingDemo_proto_rawDescGZIP() []byte {
	file_serverStreamingDemo_proto_rawDescOnce.Do(func() {
		file_serverStreamingDemo_proto_rawDescData = protoimpl.X.CompressGZIP(file_serverStreamingDemo_proto_rawDescData)
	})
	return file_serverStreamingDemo_proto_rawDescData
}

var file_serverStreamingDemo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_serverStreamingDemo_proto_goTypes = []interface{}{
	(*GetServerStreamingTextureRequest)(nil),  // 0: grpcDemo.GetServerStreamingTextureRequest
	(*GetServerStreamingTextureResponse)(nil), // 1: grpcDemo.GetServerStreamingTextureResponse
	(*GetServerStreamingMessageRequest)(nil),  // 2: grpcDemo.GetServerStreamingMessageRequest
	(*GetServerStreamingMessageResponse)(nil), // 3: grpcDemo.GetServerStreamingMessageResponse
}
var file_serverStreamingDemo_proto_depIdxs = []int32{
	0, // 0: grpcDemo.ServerStreamingDemoService.GetTexture:input_type -> grpcDemo.GetServerStreamingTextureRequest
	2, // 1: grpcDemo.ServerStreamingDemoService.GetSimpleMessage:input_type -> grpcDemo.GetServerStreamingMessageRequest
	1, // 2: grpcDemo.ServerStreamingDemoService.GetTexture:output_type -> grpcDemo.GetServerStreamingTextureResponse
	3, // 3: grpcDemo.ServerStreamingDemoService.GetSimpleMessage:output_type -> grpcDemo.GetServerStreamingMessageResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_serverStreamingDemo_proto_init() }
func file_serverStreamingDemo_proto_init() {
	if File_serverStreamingDemo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_serverStreamingDemo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerStreamingTextureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serverStreamingDemo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerStreamingTextureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serverStreamingDemo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerStreamingMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serverStreamingDemo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerStreamingMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_serverStreamingDemo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_serverStreamingDemo_proto_goTypes,
		DependencyIndexes: file_serverStreamingDemo_proto_depIdxs,
		MessageInfos:      file_serverStreamingDemo_proto_msgTypes,
	}.Build()
	File_serverStreamingDemo_proto = out.File
	file_serverStreamingDemo_proto_rawDesc = nil
	file_serverStreamingDemo_proto_goTypes = nil
	file_serverStreamingDemo_proto_depIdxs = nil
}
